try:
    a=5
    b='0'
    print(a/b)
except:
    print("Some Error Occured")
    
print("Out of try and except block")
